# Generated by Django 3.2.5 on 2021-07-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurante',
            new_name='Estabelecimento',
        ),
    ]
